version: "3.6"
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - php-fpm
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - /Users/lingb/code/html:/var/www/html
  php-fpm:
    build: ./php
    restart: always
    volumes:
      - ./php/php-fpm.conf:/etc/php/7.2/fpm/php-fpm.conf
      - ./php/php.ini-${ENV}:/usr/local/etc/php/php.ini
      - ./php/conf.d:/usr/local/etc/php/conf.d
      - ./php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./logs/php:/var/log
      - /Users/lingb/code/html:/var/www/html
    ports:
      - 9000:9000
    links:
      - db
      - cache
  cache:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    environment:
      REDIS_PROT: 6379
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
volumes:
  db: